Color :: Vector4;

// ----------------------------------------------------------------------------: basic color

BLACK :: Vector4.{0, 0, 0, 1};
WHITE :: Vector4.{1, 1, 1, 1};
RED   :: Vector4.{1, 0, 0, 1};
GREEN :: Vector4.{0, 1, 0, 1};
BLUE  :: Vector4.{0, 0, 1, 1};
CYAN :: Vector4.{0, 1, 1, 1};

ORANGE :: Vector4.{0.92, 0.54, 0.19, 1};

// ----------------------------------------------------------------------------: colors in game

BACKGROUND_COLOR :: Vector4.{0, 0.27, 0.41, 1};
DEBUG_TEXT_COLOR :: Vector4.{0.6, 1, 0.6, 0.9};
